"""
Dump golden vectors from the **normative** Python tapping engine
(WEB_PLATFORM_PLAN.md §3, "the parity discipline").

    python participant/tests/make_vectors.py

Writes participant/tests/vectors.json: synthetic distance signals plus the
detector and metric output Python produces for each. `parity.mjs` replays the
same inputs through the JS port and asserts agreement.

Regenerate this whenever the Python engine changes — Python lands first, then
the vectors, then the JS.
"""

from __future__ import annotations

import json
import math
import random
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_REPO_ROOT))

from core.tapping.detector import Calibrator, TapDetector, thumb_index_distance
from core.tapping.metrics import compute_metrics
from core.tapping.modes import MODES

OUT = Path(__file__).resolve().parent / "vectors.json"
FPS = 30.0


def signal(rate_hz: float, seconds: float, jitter: float, seed: int,
           amp: float = 1.0, drift: float = 0.0) -> list[tuple[float, float]]:
    """A synthetic thumb-index distance trace: open ≈ 1.0, closed ≈ 0.15."""
    rng = random.Random(seed)
    samples = []
    phase = 0.0
    t = 0.0
    while t < seconds:
        step = rate_hz * (1.0 + drift * t) * (1.0 + rng.uniform(-jitter, jitter))
        phase += step / FPS
        d = 0.15 + amp * 0.85 * (0.5 - 0.5 * math.cos(2 * math.pi * phase))
        samples.append((round(t, 6), round(d, 6)))
        t += 1.0 / FPS
    return samples


def landmark_case(seed: int) -> dict:
    """A 21-landmark frame, to pin thumb_index_distance()'s normalisation."""
    rng = random.Random(seed)
    pts = [[round(rng.uniform(0.1, 0.9), 6), round(rng.uniform(0.1, 0.9), 6),
            round(rng.uniform(-0.1, 0.1), 6)] for _ in range(21)]
    return {"landmarks": pts, "expect": thumb_index_distance(pts)}


def run_case(name: str, mode_key: str, samples: list[tuple[float, float]]) -> dict:
    mode = MODES[mode_key]

    cal = Calibrator()
    for t, d in samples[:90]:
        cal.update(t, d)
    d_closed, d_open = cal.result()

    det = TapDetector(mode.min_intertap_s, 0.4, d_closed, d_open)
    taps_flagged = []
    for t, d in samples:
        if det.update(t, d):
            taps_flagged.append(round(t, 6))

    metrics = compute_metrics(mode, det.tap_times, det.series,
                              samples[0][0], samples[-1][0])
    return {
        "name": name,
        "mode": mode_key,
        "samples": samples,
        "calibration": {
            "d_closed": d_closed, "d_open": d_open,
            "cycles": cal.cycles, "done": cal.done,
            "progress": cal.progress, "range_seen": cal.range_seen,
        },
        "detector": {
            "close_at": det.close_at, "open_at": det.open_at,
            "tap_times": taps_flagged, "smoothed": det.smoothed,
        },
        "metrics": metrics,
    }


def main() -> None:
    cases = [
        run_case("steady_5hz", "big_and_fast", signal(5.0, 10.0, 0.02, 1)),
        run_case("variable_4hz", "big_and_fast", signal(4.0, 10.0, 0.25, 2)),
        run_case("slowing", "big_and_fast", signal(5.0, 10.0, 0.05, 3, drift=-0.04)),
        run_case("too_few_taps", "big_and_fast", signal(0.6, 6.0, 0.02, 4)),
        run_case("small_amplitude", "big_and_fast", signal(5.0, 10.0, 0.08, 5, amp=0.55)),
        # 0.4 Hz: enough taps to be scored, too slow to have a rhythm. Guards
        # the min_effort_hz gate on both sides of the port.
        run_case("below_rhythm_floor", "big_and_fast", signal(0.4, 25.0, 0.02, 6)),
    ]
    payload = {
        "note": "Generated by participant/tests/make_vectors.py — do not hand-edit.",
        "fps": FPS,
        "modes": {k: {"key": m.key, "paced": m.paced, "duration_s": m.duration_s,
                      "expected_rate_hz": m.expected_rate_hz, "min_taps": m.min_taps,
                      "trim_taps": m.trim_taps, "cv_typical": m.cv_typical,
                      "cv_monitor": m.cv_monitor,
                      "max_rate_hz": m.max_rate_hz,
                      "min_effort_hz": m.min_effort_hz,
                      "min_intertap_s": m.min_intertap_s, "max_iti_ms": m.max_iti_ms}
                  for k, m in MODES.items()},
        "landmark_cases": [landmark_case(s) for s in (11, 12, 13)],
        "cases": cases,
    }
    OUT.write_text(json.dumps(payload, indent=1), encoding="utf-8")
    print(f"wrote {OUT.relative_to(_REPO_ROOT)}  ({OUT.stat().st_size // 1024} KB)")
    for case in cases:
        m = case["metrics"]
        print(f"  {case['name']:<16} taps={m['taps']:<3} "
              f"cv={m['cv_pct'] and round(m['cv_pct'], 3)} scoreable={m['scoreable']}")


if __name__ == "__main__":
    main()
